version: "3.9"
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_FILE: "/app/data/db.sqlite"
      PORT: 3000
    volumes:
      - ../data:/app/data
