version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
      - ./data:/app/data
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
